type Subscription {
  id: ID!
  user: User
  startDate: DateTime
  interval: String
  paymentMethod: PaymentMethod
  amount: Float
  nextPaymentDate: DateTime
  donations: [Donation]
  totalDonated: Float
  createdAt: DateTime
  updatedAt: DateTime    
}